services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: cvms_tracker_dev_image
    container_name: cvms_tracker_dev_container
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles
    ports:
      - "8003:8000"
    # env_file:
    #   - .envs/.local/.django
    #   - .envs/.local/.postgres
    # command: /entrypoint
    networks:
      - cvms_django_network

networks:
  cvms_django_network:
    external: true
