on:
  push:
    branches:
      - staging


name: Deploy cvms-tracker service
jobs:
  deploy:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build & Push Django cvms-tracker to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "./docker/staging/django/Dockerfile"
          IMAGE_NAME: "afripoint/cvms_tracker_staging_image"
          LATEST: "true"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 62.84.178.95
          username: root
          port: 22
          password: kzQdG6Vw4vJQx56obn885jCnuP65
          script: |
            cd /root/cvmstracker/cvms_tracker_config
            git checkout staging
            git reset --hard HEAD
            docker stack rm cvmstrackerstagingstack
            docker system prune
            git pull origin staging
            docker stack deploy -c /root/cvmstracker/cvms_tracker_config/docker-compose.yml cvmstrackerstagingstack 

          
